name: Reward Contributor
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  reward:
    steps:
      - name : Rewarding Action
        uses : ./actions
      
