name: Reward Contributor
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  reward:
    runs-on : ubuntu-latest
    name : A job to reward the contributor
    steps:
      - uses : actions/checkout@v1
      - name : checkout action
      - name : Rewarding Action
        uses : ./actions
      
