name: Reward Contributor
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  reward:
    runs-on : ubuntu-latest
    name : A job to reward the contributor
    steps:
      - name : Checking out 
        uses : actions/checkout@v1
      - name : Rewarding Action
        uses : ./actions
      
